[biophysical_constants]
transcription_saturation_constant=0.036                # units: µM
characteristic_transcript_length=1000                  # units: nt 
energy_promoter_state_1=20.0                           # units: kJ/mol
energy_promoter_state_2=-28.8                          # units: kJ/mol
inducer_dissociation_constant=24.19                    # units: µM CHECK
inducer_cooperativity_parameter=1.53                    # units: dimensionless
mRNA_half_life_in_min = 600                             # units: SECONDS
RNAPII_concentration=0.07                               # units: µM
transcription_elongation_rate=20                        # units: nt/s
transcription_time_constant=0.6                       # units: dimensionless
gene_length_in_nt=690                                   # units: nt
